# Generated by Django 5.0 on 2024-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_specific_keywords",
            field=models.JSONField(default=dict),
        ),
    ]
